/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Exercise {
  'id' : bigint,
  'name' : string,
  'reps' : bigint,
  'sets' : bigint,
  'weightKg' : number,
}
export type Time = bigint;
export interface UserProfile {
  'name' : string,
  'createdAt' : Time,
  'startWeight' : number,
  'weeklyWorkoutFrequency' : bigint,
  'targetWeight' : number,
  'dailyDurationHours' : number,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface WeightEntry { 'weightKg' : number, 'timestamp' : Time }
export interface WorkoutCompletionRecord { 'completions' : Array<boolean> }
export interface WorkoutContent { 'days' : Array<WorkoutDay> }
export interface WorkoutDay {
  'sections' : Array<WorkoutSection>,
  'dayName' : string,
}
export interface WorkoutSection {
  'name' : string,
  'exercises' : Array<Exercise>,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addWeightEntry' : ActorMethod<[number], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'clearCustomWorkoutForDate' : ActorMethod<[string], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getLatestWeight' : ActorMethod<[], [] | [WeightEntry]>,
  'getProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getWeightEntries' : ActorMethod<[], Array<WeightEntry>>,
  'getWorkoutCompletionCount' : ActorMethod<[], bigint>,
  'getWorkoutCompletionForDate' : ActorMethod<[string], boolean>,
  'getWorkoutCompletionsForDateRange' : ActorMethod<
    [string, string],
    Array<[string, boolean]>
  >,
  'getWorkoutForDate' : ActorMethod<[string], [] | [WorkoutContent]>,
  'getWorkoutRecords' : ActorMethod<[], Array<WorkoutCompletionRecord>>,
  'getWorkoutStreak' : ActorMethod<[], bigint>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isWorkoutSkippedForDate' : ActorMethod<[string], boolean>,
  'markWorkoutCompleted' : ActorMethod<[], undefined>,
  'markWorkoutCompletedForDate' : ActorMethod<[string], undefined>,
  'markWorkoutIncompleteForDate' : ActorMethod<[string], undefined>,
  'resetWorkoutRecords' : ActorMethod<[], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveCustomWorkoutForDate' : ActorMethod<[string, WorkoutContent], undefined>,
  'setWorkoutSkippedForDate' : ActorMethod<[string, boolean], undefined>,
  'toggleWorkoutCompletionForDate' : ActorMethod<[string], undefined>,
  'toggleWorkoutSkippedForDate' : ActorMethod<[string], boolean>,
  'updateDefaultProfile' : ActorMethod<[], undefined>,
  'updateProfile' : ActorMethod<
    [string, number, number, bigint, number],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];