/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'createdAt' : Time,
  'startWeight' : IDL.Float64,
  'weeklyWorkoutFrequency' : IDL.Int,
  'targetWeight' : IDL.Float64,
  'dailyDurationHours' : IDL.Float64,
});
export const WeightEntry = IDL.Record({
  'weightKg' : IDL.Float64,
  'timestamp' : Time,
});
export const Exercise = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'reps' : IDL.Int,
  'sets' : IDL.Int,
  'weightKg' : IDL.Float64,
});
export const WorkoutSection = IDL.Record({
  'name' : IDL.Text,
  'exercises' : IDL.Vec(Exercise),
});
export const WorkoutDay = IDL.Record({
  'sections' : IDL.Vec(WorkoutSection),
  'dayName' : IDL.Text,
});
export const WorkoutContent = IDL.Record({ 'days' : IDL.Vec(WorkoutDay) });
export const WorkoutCompletionRecord = IDL.Record({
  'completions' : IDL.Vec(IDL.Bool),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addWeightEntry' : IDL.Func([IDL.Float64], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'clearCustomWorkoutForDate' : IDL.Func([IDL.Text], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getLatestWeight' : IDL.Func([], [IDL.Opt(WeightEntry)], ['query']),
  'getProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getWeightEntries' : IDL.Func([], [IDL.Vec(WeightEntry)], ['query']),
  'getWorkoutCompletionCount' : IDL.Func([], [IDL.Int], ['query']),
  'getWorkoutCompletionForDate' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'getWorkoutCompletionsForDateRange' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Bool))],
      ['query'],
    ),
  'getWorkoutForDate' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(WorkoutContent)],
      ['query'],
    ),
  'getWorkoutRecords' : IDL.Func(
      [],
      [IDL.Vec(WorkoutCompletionRecord)],
      ['query'],
    ),
  'getWorkoutStreak' : IDL.Func([], [IDL.Int], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isWorkoutSkippedForDate' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'markWorkoutCompleted' : IDL.Func([], [], []),
  'markWorkoutCompletedForDate' : IDL.Func([IDL.Text], [], []),
  'markWorkoutIncompleteForDate' : IDL.Func([IDL.Text], [], []),
  'resetWorkoutRecords' : IDL.Func([], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveCustomWorkoutForDate' : IDL.Func([IDL.Text, WorkoutContent], [], []),
  'setWorkoutSkippedForDate' : IDL.Func([IDL.Text, IDL.Bool], [], []),
  'toggleWorkoutCompletionForDate' : IDL.Func([IDL.Text], [], []),
  'toggleWorkoutSkippedForDate' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'updateDefaultProfile' : IDL.Func([], [], []),
  'updateProfile' : IDL.Func(
      [IDL.Text, IDL.Float64, IDL.Float64, IDL.Int, IDL.Float64],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'createdAt' : Time,
    'startWeight' : IDL.Float64,
    'weeklyWorkoutFrequency' : IDL.Int,
    'targetWeight' : IDL.Float64,
    'dailyDurationHours' : IDL.Float64,
  });
  const WeightEntry = IDL.Record({
    'weightKg' : IDL.Float64,
    'timestamp' : Time,
  });
  const Exercise = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'reps' : IDL.Int,
    'sets' : IDL.Int,
    'weightKg' : IDL.Float64,
  });
  const WorkoutSection = IDL.Record({
    'name' : IDL.Text,
    'exercises' : IDL.Vec(Exercise),
  });
  const WorkoutDay = IDL.Record({
    'sections' : IDL.Vec(WorkoutSection),
    'dayName' : IDL.Text,
  });
  const WorkoutContent = IDL.Record({ 'days' : IDL.Vec(WorkoutDay) });
  const WorkoutCompletionRecord = IDL.Record({
    'completions' : IDL.Vec(IDL.Bool),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addWeightEntry' : IDL.Func([IDL.Float64], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'clearCustomWorkoutForDate' : IDL.Func([IDL.Text], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getLatestWeight' : IDL.Func([], [IDL.Opt(WeightEntry)], ['query']),
    'getProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getWeightEntries' : IDL.Func([], [IDL.Vec(WeightEntry)], ['query']),
    'getWorkoutCompletionCount' : IDL.Func([], [IDL.Int], ['query']),
    'getWorkoutCompletionForDate' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'getWorkoutCompletionsForDateRange' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Bool))],
        ['query'],
      ),
    'getWorkoutForDate' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(WorkoutContent)],
        ['query'],
      ),
    'getWorkoutRecords' : IDL.Func(
        [],
        [IDL.Vec(WorkoutCompletionRecord)],
        ['query'],
      ),
    'getWorkoutStreak' : IDL.Func([], [IDL.Int], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isWorkoutSkippedForDate' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'markWorkoutCompleted' : IDL.Func([], [], []),
    'markWorkoutCompletedForDate' : IDL.Func([IDL.Text], [], []),
    'markWorkoutIncompleteForDate' : IDL.Func([IDL.Text], [], []),
    'resetWorkoutRecords' : IDL.Func([], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveCustomWorkoutForDate' : IDL.Func([IDL.Text, WorkoutContent], [], []),
    'setWorkoutSkippedForDate' : IDL.Func([IDL.Text, IDL.Bool], [], []),
    'toggleWorkoutCompletionForDate' : IDL.Func([IDL.Text], [], []),
    'toggleWorkoutSkippedForDate' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'updateDefaultProfile' : IDL.Func([], [], []),
    'updateProfile' : IDL.Func(
        [IDL.Text, IDL.Float64, IDL.Float64, IDL.Int, IDL.Float64],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };