/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface WorkoutSection {
    name: string;
    exercises: Array<Exercise>;
}
export interface Exercise {
    id: bigint;
    name: string;
    reps: bigint;
    sets: bigint;
    weightKg: number;
}
export type Time = bigint;
export interface WorkoutContent {
    days: Array<WorkoutDay>;
}
export interface WorkoutCompletionRecord {
    completions: Array<boolean>;
}
export interface WeightEntry {
    weightKg: number;
    timestamp: Time;
}
export interface UserProfile {
    name: string;
    createdAt: Time;
    startWeight: number;
    weeklyWorkoutFrequency: bigint;
    targetWeight: number;
    dailyDurationHours: number;
}
export interface WorkoutDay {
    sections: Array<WorkoutSection>;
    dayName: string;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addWeightEntry(weight: number): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    clearCustomWorkoutForDate(date: string): Promise<void>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getLatestWeight(): Promise<WeightEntry | null>;
    getProfile(): Promise<UserProfile | null>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getWeightEntries(): Promise<Array<WeightEntry>>;
    getWorkoutCompletionCount(): Promise<bigint>;
    getWorkoutCompletionForDate(date: string): Promise<boolean>;
    getWorkoutCompletionsForDateRange(startDate: string, endDate: string): Promise<Array<[string, boolean]>>;
    getWorkoutForDate(date: string): Promise<WorkoutContent | null>;
    getWorkoutRecords(): Promise<Array<WorkoutCompletionRecord>>;
    getWorkoutStreak(): Promise<bigint>;
    isCallerAdmin(): Promise<boolean>;
    isWorkoutSkippedForDate(date: string): Promise<boolean>;
    markWorkoutCompleted(): Promise<void>;
    markWorkoutCompletedForDate(date: string): Promise<void>;
    markWorkoutIncompleteForDate(date: string): Promise<void>;
    resetWorkoutRecords(): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    saveCustomWorkoutForDate(date: string, workout: WorkoutContent): Promise<void>;
    setWorkoutSkippedForDate(date: string, skipped: boolean): Promise<void>;
    toggleWorkoutCompletionForDate(date: string): Promise<void>;
    toggleWorkoutSkippedForDate(date: string): Promise<boolean>;
    updateDefaultProfile(): Promise<void>;
    updateProfile(name: string, weight: number, targetWeight: number, frequency: bigint, duration: number): Promise<void>;
}
import type { UserProfile as _UserProfile, UserRole as _UserRole, WeightEntry as _WeightEntry, WorkoutContent as _WorkoutContent } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addWeightEntry(arg0: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addWeightEntry(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addWeightEntry(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async clearCustomWorkoutForDate(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.clearCustomWorkoutForDate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearCustomWorkoutForDate(arg0);
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLatestWeight(): Promise<WeightEntry | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getLatestWeight();
                return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLatestWeight();
            return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProfile();
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProfile();
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWeightEntries(): Promise<Array<WeightEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getWeightEntries();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWeightEntries();
            return result;
        }
    }
    async getWorkoutCompletionCount(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getWorkoutCompletionCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWorkoutCompletionCount();
            return result;
        }
    }
    async getWorkoutCompletionForDate(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.getWorkoutCompletionForDate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWorkoutCompletionForDate(arg0);
            return result;
        }
    }
    async getWorkoutCompletionsForDateRange(arg0: string, arg1: string): Promise<Array<[string, boolean]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getWorkoutCompletionsForDateRange(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWorkoutCompletionsForDateRange(arg0, arg1);
            return result;
        }
    }
    async getWorkoutForDate(arg0: string): Promise<WorkoutContent | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getWorkoutForDate(arg0);
                return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWorkoutForDate(arg0);
            return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWorkoutRecords(): Promise<Array<WorkoutCompletionRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getWorkoutRecords();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWorkoutRecords();
            return result;
        }
    }
    async getWorkoutStreak(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getWorkoutStreak();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWorkoutStreak();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isWorkoutSkippedForDate(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isWorkoutSkippedForDate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isWorkoutSkippedForDate(arg0);
            return result;
        }
    }
    async markWorkoutCompleted(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markWorkoutCompleted();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markWorkoutCompleted();
            return result;
        }
    }
    async markWorkoutCompletedForDate(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markWorkoutCompletedForDate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markWorkoutCompletedForDate(arg0);
            return result;
        }
    }
    async markWorkoutIncompleteForDate(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markWorkoutIncompleteForDate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markWorkoutIncompleteForDate(arg0);
            return result;
        }
    }
    async resetWorkoutRecords(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.resetWorkoutRecords();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.resetWorkoutRecords();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async saveCustomWorkoutForDate(arg0: string, arg1: WorkoutContent): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCustomWorkoutForDate(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCustomWorkoutForDate(arg0, arg1);
            return result;
        }
    }
    async setWorkoutSkippedForDate(arg0: string, arg1: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setWorkoutSkippedForDate(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setWorkoutSkippedForDate(arg0, arg1);
            return result;
        }
    }
    async toggleWorkoutCompletionForDate(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleWorkoutCompletionForDate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleWorkoutCompletionForDate(arg0);
            return result;
        }
    }
    async toggleWorkoutSkippedForDate(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleWorkoutSkippedForDate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleWorkoutSkippedForDate(arg0);
            return result;
        }
    }
    async updateDefaultProfile(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateDefaultProfile();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateDefaultProfile();
            return result;
        }
    }
    async updateProfile(arg0: string, arg1: number, arg2: number, arg3: bigint, arg4: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProfile(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProfile(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
}
function from_candid_UserRole_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_WeightEntry]): WeightEntry | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_WorkoutContent]): WorkoutContent | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
